# fly.toml app configuration file generated for bumpinthedark-diceroller-server on 2023-10-20T11:26:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bumpinthedark-diceroller-server"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
